/*
 * Copyright (C) 2019 Max 'Libra' Kersten [@LibraAnalysis]
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package model.mitre;

/**
 * In here, all techniques are enumerated. As comments, all tactics are listed
 * as well, although this is not required. Some techniques might be commented
 * out because they're declared before and would otherwise be a duplicate.
 *
 * The MITRE ATT&CK Matrices from April 2019 is used in this class.
 *
 * @author Max 'Libra' Kersten [@LibraAnalysis]
 */
public enum Technique {
    /**
     * InitialAccess tactic
     */
    DriveByCompromise,
    ExploitPublicFacingApplication,
    HardwareAdditions,
    ReplicationThroughRemovableMedia,
    SpearphishingAttachment,
    SpearphishingLink,
    SpearphishingViaService,
    SupplyChainCompromise,
    TrustedReleationship,
    ValidAccounts,
    /**
     * Execution tactic
     */
    AppleScript,
    CMSTP,
    CommandLineInterface,
    CompiledHtmlFile,
    ControlPanelItems,
    DynamicDataExchange,
    ExecutionThroughApi,
    ExecutionThroughModuleLoad,
    ExploitationForClientExecution,
    GraphicalUserInterface,
    InstallUtil,
    LsassDriver,
    Launchctl,
    LocalJobScheduling,
    Mshta,
    Powershell,
    RegsvcsOrRegasm,
    Regsvr32,
    Rundll32,
    ScheduledTask,
    Scripting,
    ServiceExecution,
    SignedBinaryProxyExecution,
    Source,
    SpaceAfterFilename,
    ThirdPartSoftware,
    Trap,
    TrustedDeveloperUtilities,
    UserExecution,
    WindowsManagementInstrumentation,
    WindowsRemoteManagement,
    XlsScriptProcessing,
    /**
     * Persistence tactic
     */
    BashProfile,
    Bashrc,
    AccessibilityFeatures,
    AccountManipulation,
    AppCertDlls,
    AppInitDlls,
    ApplicationShimming,
    AuthenticationPackage,
    BitsJobs,
    Bootkit,
    BrowserExtensions,
    ChangeDefaultFileAssociation,
    ComponentFirmware,
    ComponentObjectModelHijacking,
    CreateAccount,
    DllSearchOrderHijacking,
    DylibHijacking,
    ExternalRemoteServices,
    FileSystemPermissionsWeakness,
    HiddenFilesAndDirectories,
    Hooking,
    Hypervisor,
    ImageFileExecutionOptionsInjection,
    ImplantContainerImage,
    KernelModulesAndExtensions,
    LcLoadDylibAddition,
    //LsassDriver,
    LaunchAgent,
    LaunchDaemon,
    //Launchctl,
    //LocalJobScheduling,
    LoginItem,
    LogonScripts,
    ModifyExistingService,
    NetshHelperDll,
    NewService,
    OfficeApplicationStartup,
    PathInterception,
    PlistModification,
    PortKnocking,
    PortMonitors,
    RcCommon,
    ReopenedApplications,
    RedundantAccess,
    RegistryRunKeys,
    StartupFolder,
    SipAndTrustProviderHijacking,
    //ScheduledTask,
    Screensaver,
    SecuritySupportProvider,
    ServerSoftwareComponent,
    ServiceRegistryPermissionsWeakness,
    SetuidAndSetgid,
    ShortcutModification,
    StartupItems,
    SystemdService,
    SystemFirmware,
    TimeProviders,
    //Trap,
    //ValidAccounts,
    WebShell,
    WindowsManagementInstrumentationEventSubscription,
    WinlogonHelperDll,
    /**
     * Privilege Escalation tactic
     */
    AccessTokenManipulation,
    //AccessibilityFeatures,
    //AppCertDlls,
    //AppInitDlls,
    //ApplicationShimming,
    BypassUserAccountControl,
    //DllSearchOrderHijacking,
    //DylibHijacking,
    ElevatedExecutionWithPrompt,
    Emond,
    ExploitationForPrivilegeEscalation,
    ExtraWindowMemoryInjection,
    //FileSystemPermissionsWeakness,
    //Hooking,
    //ImageFileExecutionOptionsInjection,
    //LaunchDaemon,
    //NewService,
    ParentPidSpoofing,
    //PathInterception,
    //PlistModification,
    //PortMonitors,
    PowershellProfile,
    ProcessInjection,
    SidHistoryInjection,
    //ScheduledTask,
    //ServiceRegistryPermissionsWeakness,
    //SetuidAndSetgid,
    //StartupItems,
    SudoCaching,
    Sudo,
    //ValidAccounts,
    //WebShell,
    /**
     * Defense Evasion tactic
     */
    //AccessTokenManipulation,
    ApplicationAccessToken,
    //BitsJobs,
    BinaryPadding,
    //BypassUserAccountControl,
    Cmstp,
    ClearCommandHistory,
    CodeSigning,
    //CompiledHtmlFile,
    CompileAfterDelivery,
    //ComponentFirmware,
    //ComponentObjectModelHijacking,
    //ControlPanelItems,
    DcShadow,
    //DllSearchOrderHijacking,
    DllSideLoading,
    DeobfuscateOrDecodeFilesOrInformation,
    DisablingSecurityTools,
    ExecutionGuardrails,
    ExploitationForDefenseEvasion,
    //ExtraWindowMemoryInjection,
    FileDeletion,
    FilePermissionsModification,
    FileSystemLogicalOffsets,
    GatekeeperBypass,
    GroupPolicyModification,
    Histcontrol,
    //HiddenFilesAndDirectories,
    HiddenUsers,
    HiddenWindow,
    //ImageFileExecutionOptionsInjection,
    IndicatorBlocking,
    IndicatorRemovalFromTools,
    IndicatorRemovalOnHost,
    IndirectCommandExecution,
    InstallRootCertificate,
    //InstallUtil,
    LcMainHijacking,
    //Launchctl,
    Masquerading,
    ModifyRegistry,
    //Mshta,
    NtfsFileAttributes,
    NetworkShareConnectionRemoval,
    ObfuscatedFilesOrInformation,
    //PlistModification,
    //PortKnocking,
    ProcessDoppelganging,
    ProcessHollowing,
    //    ProcessInjection,
    //    RedundantAccess,
    //    RegsvcsOrRegasm,
    //    Regsvr32,
    RevertCloudInstance,
    Rootkit,
    //    Rundll32,
    //    SipAndTrustProviderHijacking,
    //    Scripting,
    //    SignedBinaryProxyExecution,
    SignedScriptProxyExecution,
    SoftwarePacking,
    //SpaceAfterFilename,
    TemplateInjection,
    Timestomp,
    //    TrustedDeveloperUtilities,
    UnusedOrUnsupportedCloudRegions,
    //    ValidAccounts,
    VirtualisationAndSandboxEvasion,
    WebService,
    WebSessionCookie,
    XslScriptProcessing,
    /**
     * CredentialAccess tactic
     */
    //AccountManipulation,
    BashHistory,
    BruteForce,
    CloudInstanceMetadataApi,
    CredentialDumping,
    CredentialsFromWebBrowsers,
    CredentialsInFiles,
    CredentialsInRegistry,
    ExploitationForCredentialAccess,
    ForcedAutehntication,
    //Hooking,
    InputCapture,
    InputPrompt,
    Kerberoasting,
    Keychain,
    LlmnrNbtnsPoisoning,
    NetworkSniffing,
    PasswordFilterDll,
    PrivateKeys,
    SecuritydMemory,
    StealApplicationAccessToken,
    StealWebSessionCookie,
    TwoFactorAuthenticationInterception,
    /**
     * Discovery tactic
     */
    AccountDiscovery,
    ApplicationWindowDiscovey,
    BrowserBookmarkDiscovery,
    CloudServiceDashboard,
    CloudServiceDiscovery,
    DomainTrustDiscovery,
    //VirtualisationAndSandboxEvasion,
    FileAndDirectoryDiscovery,
    NetworkServiceScanning,
    NetworkShareDiscovery,
    //NetworkSniffing,
    PasswordPolicyDiscovery,
    PeripheralDeviceDiscovery,
    PermissionGroupsDiscovery,
    ProcessDiscovery,
    QueryRegistry,
    RemoteSystemDiscovery,
    SecuritySoftwareDiscovery,
    SoftwareDiscovery,
    SystemInformationDiscovery,
    SystemNetworkConfigurationDiscovery,
    SystemNetworkConnectionsDiscovery,
    SystemOwnerOrUserDiscovery,
    SystemServiceDiscovery,
    SystemTimeDiscovery,
    /**
     * Lateral movement tactic
     */
    //ApplicationAccessToken,
    //AppleScript,
    ApplicationDeploymentSoftware,
    DistributedComponentObjectModel,
    ExploitationOfRemoteServices,
    InternalSpearphishing,
    //LogonScripts,
    PassTheHash,
    PassTheTicket,
    RemoteDesktopProtocol,
    RemoteFileCopy,
    RemoteServices,
    //ReplicationThroughRemovableMedia,
    SshHijacking,
    SharedWebroot,
    TaintSharedContent,
    ThirdPartySoftware,
    WindowsAdminShares,
    //WindowsRemoteManagement,
    /**
     * Collection tactic
     */
    AudioCapture,
    AutomatedCollection,
    ClipboardData,
    DataFromCloudStorageObject,
    DataStaged,
    DataFromInformationRepositories,
    DataFromLocalSystem,
    DataFromNetworkSharedDrive,
    DataFromRemovableMedia,
    EmailCollection,
    //InputCapture,
    ManInTheBrowser,
    ScreenCapture,
    VideoCapture,
    /**
     * Exfiltration tactic
     */
    AutomatedExfiltration,
    DataCompressed,
    DataEncrypted,
    DataTransferSizeLimits,
    ExfiltrationOverAlternativeProtocol,
    ExfiltrationOverCommandAndControlChannel,
    ExfiltrationOverOtherNetworkMedium,
    ExfiltrationOverPhysicalMedium,
    ScheduledTransfer,
    TransferDataToCloudAccount,
    /**
     * Command and Control tactic
     */
    CommonlyUsedPort,
    CommunicationThroughRemovableMedia,
    ConnetionProxy,
    CustomCommandAndControlProtocol,
    CustomCryptographicProtocol,
    DataEncoding,
    DataObfuscation,
    DomainFronting,
    DomHandler,
    DomainGenerationAlgorithems,
    FallbackChannels,
    MultiStageChannels,
    MultiHopProxy,
    MultibandCommunication,
    MultilayerEncryption,
    //PortKnocking,
    RemoteAccessTools,
    //RemoteFileCopy,
    StandardApplicationLayerProtocol,
    StandardCryptographicProtocol,
    StandardNonApplicationLayerProtocol,
    UncommonlyUsedPort,
    //WebService
    /**
     * Impact tactic
     */
    AccountAccessRemoval,
    DataDestruction,
    DataEncryptedForImpact,
    Defacement,
    DiskContentWipe,
    DiskStructureWipe,
    EndpointDenialOfService,
    FirmwareCorruption,
    InhibitSystemRecovery,
    NetworkDenialOfService,
    ResourceHijacking,
    RuntimeDataManipulation,
    ServiceStop,
    StoredDataManipulation,
    SystemShutdownOrReboot,
    TransmittedDataManipulation
}
